language:
    - node_js
node_js:
    - "8.11"
cache:
    directories:
        - node_modules
before_install:
    - openssl aes-256-cbc -K $encrypted_8a25f8bf4b0f_key -iv $encrypted_8a25f8bf4b0f_iv
      -in deploy_rsa.enc -out deploy_rsa -d
script:
    - yarn global add codecov -g
    - yarn test --coverage && codecov
    - yarn run build
before_deploy:
    - eval "$(ssh-agent -s)"
    - mkdir -p ~/.ssh  &&  echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config
    - chmod 600 deploy_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: rsync -r --delete-after -e "ssh -i deploy_rsa -p 37009" $TRAVIS_BUILD_DIR/build/ marchenkors@45.66.10.180:/home/example/www/enrghackfullstack
    on:
        branch: master
notifications:
    slack: getfullstack:$slack_notify_key
