export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_PENDING = "UPLOAD_FILE_PENDING";
export const UPLOAD_FILE_FULFILLED = "UPLOAD_FILE_FULFILLED";
export const UPLOAD_FILE_REJECTED = "UPLOAD_FILE_REJECTED";
